import { FormEvent, useMemo, useState } from 'react';
import { ArrowLeft, BarChart3, CheckCircle2, Database, LockKeyhole, Search, ShieldCheck, Sparkles } from 'lucide-react';
import type { QuestionCard, StockHealthCardData } from './types';
import { QuestionCardsRow } from './components/QuestionCardsRow';
import { StatusBanner } from './components/StatusBanner';
import { GoldenSummaryBanner } from './components/GoldenSummaryBanner';
import { ExplanationCardsGrid } from './components/ExplanationCardsGrid';
import { ConclusionAndSources } from './components/ConclusionAndSources';

const unknownGrowth: QuestionCard={id:3,title:'۳) آیا رشد واقعی شرکت از تورم بیشتر است؟',subtitle:'مقایسه دوره جاری با دوره هم‌طول قبلی و تورم مرجع',status:'mid',statusLabel:'نامشخص',mainMetricValue:'داده مقایسه‌ای کافی نیست',comparisonDetail:'برای محاسبه، دو دوره قابل‌مقایسه و نرخ تورم دارای منبع و تاریخ لازم است.',summaryAnswer:'در نبود داده مستند، درباره رشد واقعی نتیجه‌گیری نمی‌شود.'};
function normalize(data:StockHealthCardData){const list=[...(data.questions||[])];if(!list.some(q=>q.id===3))list.push(unknownGrowth);return{...data,questions:[1,2,3].map(id=>list.find(q=>q.id===id)||{...unknownGrowth,id,title:id===1?'۱) آیا بازده سودآوری از سود بانکی بهتر است؟':id===2?'۲) آیا سود اعلام‌شده همراه با جریان نقد است؟':unknownGrowth.title})};}
export function AppPending(){
 const[query,setQuery]=useState('');const[data,setData]=useState<StockHealthCardData|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const report=useMemo(()=>data?normalize(data):null,[data]);
 async function analyze(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const response=await fetch('/api/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query,reportMode:'audited'})});const body=await response.json();if(!response.ok)throw new Error(body.error||'خطا در تحلیل');setData(normalize(body.data));requestAnimationFrame(()=>document.getElementById('analysis')?.scrollIntoView({behavior:'smooth'}));}catch(e){setError(e instanceof Error?e.message:'خطای ناشناخته');}finally{setBusy(false)}}
 return <div className="app-shell" dir="rtl"><header className="topbar"><a className="brand" href="#top"><span className="brand-mark"><BarChart3/></span><span><b>بورس‌نگار</b><small>تحلیل بنیادی شفاف</small></span></a><nav className="nav"><a href="#method">روش تحلیل</a><a href="#sources">منابع داده</a><a href="#trust">اعتمادپذیری</a></nav><div className="header-actions"><span className="credit-pill"><LockKeyhole style={{width:14,verticalAlign:'middle'}}/> ورود پیامکی در حال فعال‌سازی است</span></div></header>
 <main id="top"><section className="hero"><div className="hero-copy"><span className="eyebrow"><span/> داده واقعی بازار تهران و کدال</span><h1>صورت‌های مالی را<br/><em>قابل فهم</em> ببینید.</h1><p>سه پرسش بنیادی، منابع قابل ردگیری و نتیجه‌ای محتاطانه؛ تحلیل عمومی تا فعال‌شدن ورود پیامکی همچنان در دسترس است.</p><form className="search-box" onSubmit={analyze}><Search/><input aria-label="نماد بورسی" value={query} onChange={e=>setQuery(e.target.value)} placeholder="مثلاً فولاد، شپنا یا فملی" required maxLength={32}/><button disabled={busy}>{busy?'در حال تحلیل…':<>تحلیل نماد <ArrowLeft/></>}</button></form>{error&&<div className="error-state" role="alert">{error}</div>}<div className="trust-line"><ShieldCheck/> بازار: BrsApi <span/> صورت مالی: کدال</div></div><div className="hero-panel"><div className="panel-head"><span>ساختار گزارش</span><span className="live-dot">داده مستند</span></div>{['بازده سودآوری در برابر سود بانکی','کیفیت نقدی سود','رشد واقعی در برابر تورم'].map((x,i)=><div className="metric-row" key={x}><span className="metric-num">۰{i+1}</span><div><b>{x}</b><small>{i===2?'فقط با دوره مقایسه‌ای معتبر':'با ذکر منبع و تاریخ'}</small></div><CheckCircle2/></div>)}<div className="panel-note">در نبود داده، وضعیت نامشخص و دلیل کمبود داده نمایش داده می‌شود.</div></div></section>
 <section className="method-section" id="method"><div className="section-heading"><span>روش کار</span><h2>از داده خام تا پاسخ روشن</h2></div><div className="steps-grid">{[[Database,'گردآوری','قیمت از BrsApi و گزارش رسمی از کدال'],[BarChart3,'محاسبه','نسبت‌های deterministic و قابل حسابرسی'],[Sparkles,'توضیح','پاسخ فارسی محتاطانه، بدون توصیه قطعی']].map(([Icon,t,d],i)=><article key={String(t)}><span className="step-index">۰{i+1}</span><Icon/><h3>{t as string}</h3><p>{d as string}</p></article>)}</div></section>
 <section className="source-band" id="sources"><div><Database/><span><b>منبع بازار</b><small>BrsApi</small></span></div><div><ShieldCheck/><span><b>منبع مالی</b><small>کدال</small></span></div><p>زمان گزارش و وضعیت حسابرسی در خروجی تحلیل درج می‌شود.</p></section>
 {busy&&<section className="analysis-skeleton"><div/><div/><div/></section>}{report&&<section id="analysis" className="analysis-wrap"><div className="analysis-title"><span>گزارش بنیادی</span><h2>{report.header.fullName} <small>{report.header.symbol}</small></h2><p>{report.header.reportDate} · {report.header.dataStamp.source}</p></div><QuestionCardsRow questions={report.questions}/><StatusBanner metrics={report.statusBanner}/><GoldenSummaryBanner summary={report.goldenSummary}/><ExplanationCardsGrid cards={report.explanationCards}/><ConclusionAndSources conclusion={report.conclusion}/></section>}
 <section className="trust-section" id="trust"><div><span className="eyebrow"><span/> تعهد بورس‌نگار</span><h2>ابهام را پنهان نمی‌کنیم.</h2></div><p>ورود پیامکی تا تأیید نهایی قالب کاوه‌نگار غیرفعال است. هیچ Mock یا کد ثابت در Production استفاده نمی‌شود. این سامانه توصیه سرمایه‌گذاری نیست.</p></section></main><footer><b>بورس‌نگار</b><span>تحلیل بنیادی شفاف بازار سرمایه ایران</span><small>مسئولیت تصمیم نهایی با کاربر است.</small></footer></div>;
}
