import { useEffect, useId, useState } from "react";
import { Flag, Heart, MessageSquare, Reply } from "lucide-react";
import { api, type User } from "../AppProduction";

type Comment = { id:string; parent_id:string|null; body:string; created_at:string; user_label:string; likes:number; user_liked:boolean };
export function Comments({ kind, symbol, user, onLogin }: { kind:"site_feedback"|"symbol_comment"; symbol?:string; user:User|null; onLogin:()=>void }) {
  const editorId=useId(),[items,setItems]=useState<Comment[]>([]),[body,setBody]=useState(""),[replyTo,setReplyTo]=useState<string|null>(null),[notice,setNotice]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  const load=()=>{setLoading(true);return api<{comments:Comment[]}>(`/api/comments?kind=${kind}${symbol?`&symbol=${encodeURIComponent(symbol)}`:""}`).then(r=>setItems(Array.isArray(r?.comments)?r.comments:[])).catch(()=>setError("دریافت گفت‌وگو ممکن نشد.")).finally(()=>setLoading(false))};
  useEffect(()=>{void load()},[kind,symbol]);
  async function submit(parentId:string|null=null){if(!user){onLogin();return}setError("");setNotice("");try{await api("/api/comments",{method:"POST",body:JSON.stringify({kind,symbol,body,parentId})});setBody("");setReplyTo(null);setNotice(parentId?"پاسخ شما منتشر و به نویسنده اطلاع داده شد.":"نظر شما منتشر شد.");await load()}catch(e){setError(e instanceof Error?e.message:"خطا در ارسال نظر")}}
  async function like(c:Comment){if(!user){onLogin();return}const r=await api<{liked:boolean;likes:number}>(`/api/comments/${c.id}/like`,{method:"POST"});setItems(v=>v.map(x=>x.id===c.id?{...x,user_liked:r.liked,likes:r.likes}:x))}
  async function report(id:string){if(!user){onLogin();return}if(!window.confirm("این نظر برای بررسی مدیران گزارش شود؟"))return;await api(`/api/comments/${id}/report`,{method:"POST",body:JSON.stringify({reason:"محتوای نامناسب یا گمراه‌کننده"})});setNotice("گزارش برای بررسی ثبت شد.")}
  const roots=items.filter(c=>!c.parent_id),replies=(id:string)=>items.filter(c=>c.parent_id===id);
  const card=(c:Comment,nested=false)=><article className={nested?"comment-card comment-reply":"comment-card"} key={c.id}><div className="comment-meta"><span className="comment-avatar" aria-hidden="true">{c.user_label.slice(0,1)}</span><small><b>{c.user_label}</b><time dateTime={c.created_at}>{new Date(c.created_at).toLocaleDateString("fa-IR")}</time></small></div><p>{c.body}</p><div className="comment-actions"><button aria-label="پاسخ به این نظر" onClick={()=>{setReplyTo(c.id);setBody("")}}><Reply/> پاسخ</button><button className={c.user_liked?"liked":""} aria-pressed={c.user_liked} onClick={()=>void like(c)}><Heart/> {c.likes.toLocaleString("fa-IR")}</button><button aria-label="گزارش نظر" onClick={()=>void report(c.id)}><Flag/> گزارش</button></div>{replyTo===c.id&&<div className="reply-form"><label htmlFor={`${editorId}-${c.id}`}>پاسخ به {c.user_label}</label><textarea id={`${editorId}-${c.id}`} autoFocus value={body} onChange={e=>setBody(e.target.value)} maxLength={2000}/><span>{body.length.toLocaleString("fa-IR")} از ۲۰۰۰</span><button onClick={()=>void submit(c.id)} disabled={body.trim().length<3}>ارسال پاسخ</button></div>}{replies(c.id).map(r=>card(r,true))}</article>;
  return <section id="symbol-comments" className="comments-section"><header><MessageSquare/><div><span>{kind==="site_feedback"?"بازخورد کاربران":`${items.length.toLocaleString("fa-IR")} پیام`}</span><h2>{kind==="site_feedback"?"نظر شما درباره بورس‌نگار":"گفت‌وگوی کاربران درباره این سهم"}</h2></div></header><div className="community-note">دیدگاه‌ها متعلق به کاربران‌اند و توصیه سرمایه‌گذاری محسوب نمی‌شوند.</div><div className="comment-form"><label htmlFor={editorId}>نظر شما</label><textarea id={editorId} value={replyTo?"":body} onChange={e=>setBody(e.target.value)} maxLength={2000} placeholder={user?"تحلیل یا پرسش خود را مستند و محترمانه بنویسید…":"برای ثبت نظر ابتدا وارد شوید."}/><button onClick={()=>void submit()} disabled={body.trim().length<3}>{user?"ارسال نظر":"ورود و ارسال نظر"}</button><div aria-live="polite">{notice&&<small className="success-state">{notice}</small>}{error&&<small className="error-state">{error}</small>}</div></div><div className="comment-list">{loading?<p className="empty-docs">در حال دریافت گفت‌وگو…</p>:roots.map(c=>card(c))}{!loading&&!items.length&&<p className="empty-docs">هنوز نظری منتشر نشده؛ آغازکننده گفت‌وگو باشید.</p>}</div></section>;
}
