import { useEffect, useState } from "react";
import { Flag, MessageSquare, Reply, ThumbsUp } from "lucide-react";
import { api, type User } from "../AppProduction";

type Comment = { id:string; parent_id:string|null; body:string; created_at:string; user_label:string; likes:number };
export function Comments({ kind, symbol, user, onLogin }: { kind:"site_feedback"|"symbol_comment"; symbol?:string; user:User|null; onLogin:()=>void }) {
  const [items,setItems]=useState<Comment[]>([]); const [body,setBody]=useState(""); const [replyTo,setReplyTo]=useState<string|null>(null); const [notice,setNotice]=useState(""); const [error,setError]=useState("");
  const load=()=>api<{comments:Comment[]}>(`/api/comments?kind=${kind}${symbol?`&symbol=${encodeURIComponent(symbol)}`:""}`).then(r=>setItems(Array.isArray(r?.comments) ? r.comments : [])).catch(()=>setItems([]));
  useEffect(()=>{void load()},[kind,symbol]);
  async function submit(parentId:string|null=null){if(!user){onLogin();return;}setError("");setNotice("");try{await api("/api/comments",{method:"POST",body:JSON.stringify({kind,symbol,body,parentId})});setBody("");setReplyTo(null);setNotice("نظر شما منتشر شد.");void load()}catch(e){setError(e instanceof Error?e.message:"خطا در ارسال نظر")}}
  const roots=items.filter(c=>!c.parent_id), replies=(id:string)=>items.filter(c=>c.parent_id===id);
  const card=(c:Comment, nested=false)=><article className={nested?"comment-card comment-reply":"comment-card"} key={c.id}><p>{c.body}</p><small>{c.user_label} · {new Date(c.created_at).toLocaleDateString("fa-IR")}</small><span className="comment-actions"><button aria-label="پاسخ" onClick={()=>{setReplyTo(c.id);setBody("")}}><Reply/> پاسخ</button><ThumbsUp/> {c.likes} <Flag/></span>{replyTo===c.id&&<div className="reply-form"><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={2000} placeholder="پاسخ خود را بنویسید…"/><button onClick={()=>submit(c.id)} disabled={body.trim().length<3}>ارسال پاسخ</button></div>}{replies(c.id).map(r=>card(r,true))}</article>;
  return <section id="symbol-comments" className="comments-section"><header><MessageSquare/><div><span>{kind==="site_feedback"?"بازخورد کاربران":"گفت‌وگوی این نماد"}</span><h2>{kind==="site_feedback"?"نظر شما درباره بورس‌نگار":"گفت‌وگوی کاربران درباره این سهم"}</h2></div></header><div className="comment-form"><textarea value={replyTo?"":body} onChange={e=>setBody(e.target.value)} maxLength={2000} placeholder={user?"نظر خود را بنویسید…":"برای ثبت نظر ابتدا وارد شوید."}/><button onClick={()=>submit()} disabled={body.trim().length<3}>{user?"ارسال نظر":"ورود و ارسال نظر"}</button>{notice&&<small className="success-state">{notice}</small>}{error&&<small className="error-state">{error}</small>}</div><div className="comment-list">{roots.map(c=>card(c))}{!items.length&&<p className="empty-docs">هنوز نظری منتشر نشده است.</p>}</div></section>;
}
