import { useEffect, useState, type FormEvent } from "react";
import { Activity, ArrowLeft, BarChart3, Filter, TrendingDown, TrendingUp } from "lucide-react";
import { api } from "../AppProduction";

type Leader={symbol:string;legal_name:string;price:string;value:string;change_percent:string|null};
type Dashboard={latest_date:string;symbols:number;total_value:string;total_volume:string;advancers:number;decliners:number;unchanged:number;top_gainers:Leader[];top_losers:Leader[];top_value:Leader[]};
type Row={symbol:string;legal_name:string;industry:string;trading_date_jalali:string;price:string;volume:string;value:string;return_1m:string|null;ma20:string|null;ma50:string|null;decision:string|null;action_state:string;fundamental_strength:string;review_signal:string;analysis_state:string|null;health_score:string|null;data_coverage:string|null;confidence:string|null;fair_value_low:string|null;fair_value_base:string|null;fair_value_high:string|null;buy_zone_high:string|null;sell_zone_low:string|null;pe:string|null;roe:string|null};
const fa=(value:unknown,digits=0)=>value==null?"—":Number(value).toLocaleString("fa-IR",{maximumFractionDigits:digits});
const decisionFa:Record<string,string>={BUY:"خرید",HOLD:"نگهداری",SELL:"فروش",INSUFFICIENT_DATA:"داده ناکافی"};
const quickRead=(row:Row)=>row.action_state==="BUY"?"قیمت در محدوده خرید":row.action_state==="HOLD"?"نگهداری؛ پیگیری گزارش بعدی":row.action_state==="SELL"?"فشار فروش یا ارزش‌گذاری بالا":row.action_state==="CONDITIONAL_REVIEW"?"ارزش‌گذاری امیدوارکننده؛ روند را هم ببینید":row.action_state==="DATA_REVIEW"?"داده ناقص؛ فعلاً صبر برای تکمیل":"هنوز مبنای معتبر برای تصمیم نیست";

export function MarketExplorer(){
  const [dashboard,setDashboard]=useState<Dashboard|null>(null); const [rows,setRows]=useState<Row[]>([]); const [industries,setIndustries]=useState<string[]>([]); const [total,setTotal]=useState(0); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const [filters,setFilters]=useState({q:"",industry:"",decision:"",minReturn:"",maxPe:"",minRoe:"",minVolume:"",trend:"",sort:"value"});
  useEffect(()=>{api<Dashboard>("/api/market/dashboard").then((value)=>setDashboard(value?.latest_date ? value : null)).catch(()=>setDashboard(null));void load();},[]);
  async function load(event?:FormEvent){event?.preventDefault();setLoading(true);setError("");try{const params=new URLSearchParams();Object.entries(filters).forEach(([key,value])=>value&&params.set(key,String(value)));const data=await api<{rows:Row[];total:number;industries:string[]}>(`/api/market/screener?${params}`);setRows(Array.isArray(data.rows)?data.rows:[]);setTotal(Number(data.total)||0);setIndustries(Array.isArray(data.industries)?data.industries:[]);}catch(e){setRows([]);setTotal(0);setError(e instanceof Error?e.message:"خطا در دریافت اسکرینر");}finally{setLoading(false)}}
  const update=(key:string,value:string)=>setFilters(current=>({...current,[key]:value}));
  return <section className="market-explorer" id="market"><header className="market-heading"><span>MARKET / SCREENER</span><h2>نبض بازار، در یک نگاه</h2><p>داده‌های واقعی بازار را سریع مقایسه کن؛ انتخاب‌های پیش‌فرض بر پایه ارزش معاملات و نقدشوندگی مرتب شده‌اند.</p></header>
    {dashboard&&<><div className="market-summary"><article><Activity/><small>آخرین روز داده</small><strong>{new Date(dashboard.latest_date).toLocaleDateString("fa-IR")}</strong><em>آخرین به‌روزرسانی بازار</em></article><article><TrendingUp/><small>نمادهای مثبت</small><strong>{fa(dashboard.advancers)}</strong><em>در برابر {fa(dashboard.decliners)} نماد منفی</em></article><article><TrendingDown/><small>نمادهای منفی</small><strong>{fa(dashboard.decliners)}</strong><em>برای بررسی ریسک بازار</em></article><article><BarChart3/><small>ارزش معاملات</small><strong>{fa(Number(dashboard.total_value)/1_000_000_000,1)} میلیارد ریال</strong><em>معیار نقدشوندگی روز</em></article></div><div className="leader-grid"><LeaderList title="برندگان امروز" rows={dashboard.top_gainers}/><LeaderList title="بیشترین افت امروز" rows={dashboard.top_losers}/><LeaderList title="پول در گردش بازار" rows={dashboard.top_value}/></div></>}
    <form className="screener-filters" onSubmit={load}><label>جست‌وجو<input value={filters.q} onChange={e=>update("q",e.target.value)} placeholder="نماد یا شرکت"/></label><label>صنعت<select value={filters.industry} onChange={e=>update("industry",e.target.value)}><option value="">همه صنایع</option>{industries.map(x=><option key={x}>{x}</option>)}</select></label><label>نتیجه تحلیل<select value={filters.decision} onChange={e=>update("decision",e.target.value)}><option value="">همه</option><option value="BUY">خرید</option><option value="HOLD">نگهداری</option><option value="SELL">فروش</option></select></label><label>حداقل بازده یک‌ماهه<input type="number" value={filters.minReturn} onChange={e=>update("minReturn",e.target.value)} placeholder="درصد"/></label><label>حداکثر P/E<input type="number" min="0" step="0.1" value={filters.maxPe} onChange={e=>update("maxPe",e.target.value)}/></label><label>حداقل ROE<input type="number" step="0.1" value={filters.minRoe} onChange={e=>update("minRoe",e.target.value)} placeholder="درصد"/></label><label>حداقل حجم<input type="number" min="0" value={filters.minVolume} onChange={e=>update("minVolume",e.target.value)}/></label><label>روند<select value={filters.trend} onChange={e=>update("trend",e.target.value)}><option value="">همه</option><option value="above_ma20">بالاتر از میانگین ۲۰روزه</option><option value="above_ma50">بالاتر از میانگین ۵۰روزه</option></select></label><label>مرتب‌سازی<select value={filters.sort} onChange={e=>update("sort",e.target.value)}><option value="value">ارزش معاملات</option><option value="return">بازده یک‌ماهه</option><option value="volume">حجم</option><option value="health">سلامت بنیادی</option><option value="pe">کمترین P/E</option></select></label><button disabled={loading}><Filter/>{loading?"در حال محاسبه…":"اعمال فیلتر"}</button></form>
    {error&&<div className="error-state">{error}</div>}<div className="screener-meta">{fa(total)} نماد مطابق فیلتر · ۱۰ انتخاب برتر نمایش داده می‌شود</div><div className="screener-table"><table><thead><tr><th>نماد</th><th>قیمت</th><th>بازده ۱ ماه</th><th>محدوده خرید</th><th>محدوده فروش</th><th>P/E</th><th>ROE</th><th>بنیاد</th><th>اقدام</th><th>برداشت سریع</th></tr></thead><tbody>{rows.slice(0,10).map(row=><tr key={row.symbol}><td><a href={`/s/${encodeURIComponent(row.symbol)}`}><b>{row.symbol}</b><small>{row.legal_name}</small></a></td><td>{fa(row.price)}</td><td className={Number(row.return_1m)>=0?"positive":"negative"}>{row.return_1m==null?"—":`${fa(row.return_1m,1)}٪`}</td><td>{row.buy_zone_high?`تا ${fa(row.buy_zone_high)} ریال`:"—"}</td><td>{row.sell_zone_low?`از ${fa(row.sell_zone_low)} ریال`:"—"}</td><td>{fa(row.pe,1)}</td><td>{row.roe==null?"—":`${fa(row.roe,1)}٪`}</td><td><em data-strength={row.fundamental_strength}>{row.fundamental_strength==="STRONG"?"قوی":row.fundamental_strength==="MODERATE"?"متوسط":row.fundamental_strength==="WEAK"?"ضعیف":"نامشخص"}</em></td><td><em data-decision={row.action_state}>{row.action_state==="CONDITIONAL_REVIEW"?"بررسی مشروط":row.action_state==="NOT_EVALUABLE"?"قابل ارزیابی نیست":row.action_state==="DATA_REVIEW"?"تکمیل داده":decisionFa[row.decision||""]||"تحلیل‌نشده"}</em></td><td className="screener-read">{quickRead(row)}</td></tr>)}</tbody></table></div>
  </section>;
}
function LeaderList({title,rows}:{title:string;rows:Leader[]}){return <article><h3>{title}</h3>{(rows||[]).map(row=><a key={row.symbol} href={`/s/${encodeURIComponent(row.symbol)}`}><span><b>{row.symbol}</b><small>{row.legal_name}</small></span><em className={Number(row.change_percent)>=0?"positive":"negative"}>{row.change_percent==null?fa(Number(row.value)/1_000_000_000,1):`${fa(row.change_percent,1)}٪`}<ArrowLeft/></em></a>)}</article>}
