import { useEffect, useState, type FormEvent } from "react";
import { Activity, ArrowLeft, BarChart3, Filter, TrendingDown, TrendingUp } from "lucide-react";
import { api } from "../AppProduction";

type Leader={symbol:string;legal_name:string;price:string;value:string;change_percent:string|null};
type Dashboard={latest_date:string;symbols:number;total_value:string;total_volume:string;advancers:number;decliners:number;unchanged:number;top_gainers:Leader[];top_losers:Leader[];top_value:Leader[]};
type Row={symbol:string;legal_name:string;industry:string;trading_date_jalali:string;price:string;volume:string;value:string;return_1m:string|null;ma20:string|null;ma50:string|null;decision:string|null;health_score:string|null;pe:string|null;roe:string|null};
const fa=(value:unknown,digits=0)=>value==null?"—":Number(value).toLocaleString("fa-IR",{maximumFractionDigits:digits});
const decisionFa:Record<string,string>={BUY:"خرید",HOLD:"نگهداری",SELL:"فروش",INSUFFICIENT_DATA:"داده ناکافی"};

export function MarketExplorer(){
  const [dashboard,setDashboard]=useState<Dashboard|null>(null); const [rows,setRows]=useState<Row[]>([]); const [industries,setIndustries]=useState<string[]>([]); const [total,setTotal]=useState(0); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const [filters,setFilters]=useState({q:"",industry:"",decision:"",minReturn:"",maxPe:"",minRoe:"",minVolume:"",trend:"",sort:"value"});
  useEffect(()=>{api<Dashboard>("/api/market/dashboard").then(setDashboard).catch(()=>setDashboard(null));void load();},[]);
  async function load(event?:FormEvent){event?.preventDefault();setLoading(true);setError("");try{const params=new URLSearchParams();Object.entries(filters).forEach(([key,value])=>value&&params.set(key,String(value)));const data=await api<{rows:Row[];total:number;industries:string[]}>(`/api/market/screener?${params}`);setRows(data.rows);setTotal(data.total);setIndustries(data.industries);}catch(e){setError(e instanceof Error?e.message:"خطا در دریافت اسکرینر");}finally{setLoading(false)}}
  const update=(key:string,value:string)=>setFilters(current=>({...current,[key]:value}));
  return <section className="market-explorer" id="market"><header className="market-heading"><span>MARKET / SCREENER</span><h2>نمای بازار و اسکرینر واقعی</h2><p>همه اعداد از تاریخچه عملیاتی بورس‌نگار محاسبه می‌شوند؛ مرتب‌سازی و فیلترها سمت سرور اجرا می‌شوند.</p></header>
    {dashboard&&<><div className="market-summary"><article><Activity/><small>آخرین روز داده</small><strong>{dashboard.latest_date}</strong></article><article><TrendingUp/><small>نمادهای مثبت</small><strong>{fa(dashboard.advancers)}</strong></article><article><TrendingDown/><small>نمادهای منفی</small><strong>{fa(dashboard.decliners)}</strong></article><article><BarChart3/><small>ارزش معاملات</small><strong>{fa(Number(dashboard.total_value)/1_000_000_000,1)} میلیارد ریال</strong></article></div><div className="leader-grid"><LeaderList title="بیشترین رشد روز" rows={dashboard.top_gainers}/><LeaderList title="بیشترین افت روز" rows={dashboard.top_losers}/><LeaderList title="بیشترین ارزش معامله" rows={dashboard.top_value}/></div></>}
    <form className="screener-filters" onSubmit={load}><label>جست‌وجو<input value={filters.q} onChange={e=>update("q",e.target.value)} placeholder="نماد یا شرکت"/></label><label>صنعت<select value={filters.industry} onChange={e=>update("industry",e.target.value)}><option value="">همه صنایع</option>{industries.map(x=><option key={x}>{x}</option>)}</select></label><label>نتیجه تحلیل<select value={filters.decision} onChange={e=>update("decision",e.target.value)}><option value="">همه</option><option value="BUY">خرید</option><option value="HOLD">نگهداری</option><option value="SELL">فروش</option></select></label><label>حداقل بازده یک‌ماهه<input type="number" value={filters.minReturn} onChange={e=>update("minReturn",e.target.value)} placeholder="درصد"/></label><label>حداکثر P/E<input type="number" min="0" step="0.1" value={filters.maxPe} onChange={e=>update("maxPe",e.target.value)}/></label><label>حداقل ROE<input type="number" step="0.1" value={filters.minRoe} onChange={e=>update("minRoe",e.target.value)} placeholder="درصد"/></label><label>حداقل حجم<input type="number" min="0" value={filters.minVolume} onChange={e=>update("minVolume",e.target.value)}/></label><label>روند<select value={filters.trend} onChange={e=>update("trend",e.target.value)}><option value="">همه</option><option value="above_ma20">بالاتر از میانگین ۲۰روزه</option><option value="above_ma50">بالاتر از میانگین ۵۰روزه</option></select></label><label>مرتب‌سازی<select value={filters.sort} onChange={e=>update("sort",e.target.value)}><option value="value">ارزش معاملات</option><option value="return">بازده یک‌ماهه</option><option value="volume">حجم</option><option value="health">سلامت بنیادی</option><option value="pe">کمترین P/E</option></select></label><button disabled={loading}><Filter/>{loading?"در حال محاسبه…":"اعمال فیلتر"}</button></form>
    {error&&<div className="error-state">{error}</div>}<div className="screener-meta">{fa(total)} نماد مطابق فیلتر · حداکثر ۵۰ نتیجه نخست</div><div className="screener-table"><table><thead><tr><th>نماد</th><th>قیمت</th><th>بازده ۱ ماه</th><th>حجم</th><th>MA20</th><th>P/E</th><th>ROE</th><th>سلامت</th><th>نتیجه</th></tr></thead><tbody>{rows.map(row=><tr key={row.symbol}><td><a href={`/s/${encodeURIComponent(row.symbol)}`}><b>{row.symbol}</b><small>{row.legal_name}</small></a></td><td>{fa(row.price)}</td><td className={Number(row.return_1m)>=0?"positive":"negative"}>{row.return_1m==null?"—":`${fa(row.return_1m,1)}٪`}</td><td>{fa(row.volume)}</td><td>{fa(row.ma20)}</td><td>{fa(row.pe,1)}</td><td>{row.roe==null?"—":`${fa(row.roe,1)}٪`}</td><td>{fa(row.health_score)}</td><td><em data-decision={row.decision||"NONE"}>{decisionFa[row.decision||""]||"تحلیل‌نشده"}</em></td></tr>)}</tbody></table></div>
  </section>;
}
function LeaderList({title,rows}:{title:string;rows:Leader[]}){return <article><h3>{title}</h3>{(rows||[]).map(row=><a key={row.symbol} href={`/s/${encodeURIComponent(row.symbol)}`}><span><b>{row.symbol}</b><small>{row.legal_name}</small></span><em className={Number(row.change_percent)>=0?"positive":"negative"}>{row.change_percent==null?fa(Number(row.value)/1_000_000_000,1):`${fa(row.change_percent,1)}٪`}<ArrowLeft/></em></a>)}</article>}
